language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
deploy:
  provider: heroku
  api_key:
    secure: klL4kMhFifI/DY/oJhldk1xEGsiYoFCw9RXJHKIFsD/n/YJ22f2ZyXh8G7yG+ydhP4stdJBVDQkDj8S6dPFx33vNEXkGAVNFxjMBSVApeMajmK4IqjoOa25YLNPqHV6liUaIy8CJ3Vd+FZyImdhllutZXhRt5A0Fqewxl9byBuc=
  app: shrouded-gorge-1561
  on:
    repo: kkpb/rakuten_enpit_example
